console.log("+++ Send an FCM notification.");
var request = require('request');
//
// Before running, set the FCM project values.
// 
// My Google Firebase project: twilionotify.
//  Dashboard: https://console.firebase.google.com
//  Firebase/Project Overview(click icon)/Project setting/Cloud Messaging
//  Get value for the Server key Token.
//  The Server key Token, is the FCM Secret in a Twilio credential entry.
//  $ export FCM_SERVER_KEY_TOKEN=AAAA...x6r
//  
// Requested by the device, generated by the FCM network.
//  $ export FCM_DEVICE_TOKEN=cw...YX

var serverKeyToken = process.env.FCM_SERVER_KEY_TOKEN;
console.log('+ serverKeyToken: ' + serverKeyToken);
// var deviceToken = process.env.FCM_DEVICE_TOKEN;
//
// For this web application, the "address" is the FCM token value from: index.html.
// Firefox older FCM token, Conversations token:
// deviceFcmTokenAddress = "eQZbCbVf4tQ:APA91bHac8cXIKDPfJNsM6Ffb7py52PMA2H5ERlRF0alq_haXlToLq9p1SbafmHu0olREyPIfsU2xfCjZP8RIbt6qjuQT2Oub21rE05-yPY06b_pQd4BQ4-jVS0ciBQW-j-22XezSftK";
// Firefox current FCM token:
// deviceFcmTokenAddress = "c2h7i9H7mcI:APA91bEifCmmIObAbgLUEUys1J_KwKx1bJW3XaxcggSqbheRAQIAwLLoZWccfmRhv3xw_XrNhqHu4OrDdAMF5fQmglY7dv2HetFkZm_3YG_WK1fd0-6yQGBvvHZKFyPM02rbDePLXswX";
// Chrome browser:
deviceFcmTokenAddress = "eHdERSUFfbo:APA91bE8bKiM7nNVhe-r6SE7qDnzXUXEXjbvjv5Hp1l34sA2YUhioFyq2v5G7vR86RelXaa1g7cvSflXFMGlEqZZryu5eupUrtlmbX5HHJJ5DyB5uRGCqjg6xTtGXIGWmrRjvo1o4_Zs";
//
console.log('+ deviceToken: ' + deviceFcmTokenAddress);
//
var theRequestUrl = "https://fcm.googleapis.com/fcm/send";
console.log('+ theRequestUrl: ' + theRequestUrl);
var theMessage = "Hello there 7b";
console.log('+ theMessage: ' + theMessage);
request({
    method: "POST",
    url: theRequestUrl,
    headers: {
        "Content-type": "application/json",
        "Authorization": "key=" + serverKeyToken
    },
    json: {
        "to": deviceFcmTokenAddress,
        "notification": {"title":"Sent using a command line program.","body":theMessage}
    }
}, function (error, response, body) {
    console.log("+ body: " + JSON.stringify(body));
    // Sample success: + body: {"multicast_id":70031060372181420,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"ef9a795a-1105-415e-8c16-0eabe9e0ec2f"}]}
    // console.log("- Error: " + error.code + " - " + error.message);
    console.log("+++ Exit.");
});

// eof